### ISSUE TITLE
List of Roles on Component within Model Driven App fail after Solution import

### ISSUE THREAD

**Issue by devman2k** [cathalnoonan/d365-pcf-securityrolemanager#32]
### Description

After you import your solution the list of Roles listed in the component are truncated as the system removes the paragraph mark. Please update solution to SPLIT on a comma or semi colon rather than a paragraph mark or correct the system to no remove the paragraph mark. 

### Steps to reproduce

1. Edit the Form containing the PCF component
2. Select the PCF component, then choose Properties
3. In the Components Section Expand the SERCURITY Roles property to expose the list of Security Roles
4. Ensure that the list contains more that 3 roles separated by ENTER KEY
5. PUBLISH (then publish again)
6. Export Managed Solution
7. Import Managed Solution in new CRM Instance
8. Render the form with the Security Roles component - nothing renders due to broken list
9. Edit the Form in the new instance and note that the List of Roles no longer separated by Carriage Return Line Feeds 
![Roles are truncate Paragraph marks](https://github.com/user-attachments/assets/698b34f3-2065-4415-bb3a-31899ac7c17c)

### Screenshots

![Roles are truncate Paragraph marks](https://github.com/user-attachments/assets/ad132e68-c8ab-42ac-88a4-d7a8f01acd5a)

### Version installed

V2

**Comment by cathalnoonan** [comment]
Hi @devman2k, I remember considering this option before - whether to split on a new line, a comma, a semicolon, or something else.

In the end, I decided that a new line made most sense because that character can't be used in a security role name.

The fix will likely need you to add another property when configuring the control to say which character should be used to split the list of roles being displayed.

That character should not be one that exists in your security role names (i.e. if you want to split by comma, you shouldn't do that if you have roles that contain a comma in the name).

When there's a fix ready, I'll reply to this thread.

---

To get a bit more context on how/when the new lines are being removed from your list of filtered roles, do you mind explaining the process you follow to get the solution from environment A into environment B?

Do you:
- manually export zip, manually import zip?
- programmatically export zip, programmatically import zip?
- programmatically export zip then unpack the solution to source control, then pack the solution and programmatically import it?

I'm asking to understand exactly how to replicate the issue.

And does it only happen when there are more than 3 roles included in the list?

And more for curiously reasons, have you tried:
- using unmanaged solutions?
- removing the unmanaged layers on the form after deploying?

**Comment by devman2k** [comment]
Excellent. I agree with you that the new line was a great idea. It both presents well and is easy to understand without having to read instructions. If the app didn’t remove the Newlines I think it things be ok. I’m curious what JS is removing it. I appreciate the fix whatever you choose!

**Comment by cathalnoonan** [comment]
Hi @devman2k, this is fixed in the new release:
https://github.com/cathalnoonan/d365-pcf-securityrolemanager/releases/tag/v2.2.0

There's a new field added that you can specify a delimiter. There are screenshots added in the docs that may help.
https://github.com/cathalnoonan/d365-pcf-securityrolemanager/blob/v2.2.0/docs/installation-and-configuration.md

**Comment by devman2k** [comment]
Very much appreciated!!!

Bryan
________________________________
